---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Сайт должен иметь мобильную версию
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь должен иметь возможность переключить язык интерфейса
  - Сайт должен иметь локализацию (перевод) на русский и английский языки
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Корректное своевременное обработка остатков, чтобы посетитель интернет-магазина не мог положить в корзину товара больше, чем его есть на складе
  - Сверка количества товаров в корзине с доступными остатками на складах в момент оформления заказа, чтобы посетитель не мог заказать,
  | больше имеющегося в наличии количества, когда остатки изменились с момента добавления в корзину
  - Резервирование количества товара в момент оформления заказа, чтобы он перестал считаться доступным для других посетителей
  - Чтобы посетитель считался пользователем, он должен пройти фактическую регистрацию, даже если формально это будет называться по-другому «купить в один клик»
  | «получить одноразовый пароль по SMS», «авторизоваться через Google»»…, для однозначного сопоставления заказов с заказчиком
  - Посетитель должен быть уведомлён о действующей на сайте политике конфиденциальности. Информация о ней должна быть доступной и актуальной и до, и после того,
  | как он дал согласие на обработку персональных данных
  - После успешного оформления заказа пользователь должен получить уникальный идентификатор заказа, по которому будет возможно отслеживать его состояние или
  | оформит обращение
  - Посетитель должен быть проинформирован обо всех доступных способах оплаты и получения
  - Пользователь должен быть уведомлён о действии гарантии, правилах возврата и обмена. Информация должна быть доступной и актуальной.
  - До выбора предпочитаеомого языка интерфейса посетителем, он должен быть предложен, исходя из настроеек браузера посетителя, или его геолокации.
  - Выбранный посетителем язык должен сохраняться по крайней мере до конца сессии
  - Если в юрисдикции работы интернет-магазина действуют возрастные ограничения на некоторые категории товара, посетитель должен быть уведомлен об этом,
  | и получить доступ к их просмотру и заказу только после подтверждения возраста
